{"info": {"name": "django-exceptions", "version": "0.4", "requires_dist": ["urllib3 (<1.27,>=1.21.1)", "certifi (>=2017.4.17)\"", "chardet (<5,>=3.0.2) ; python_version < \"3\""], "requires_python": null, "platform": "UNKNOWN", "summary": null}, "releases": {"0.4": [{"filename": "django-exceptions-0.4.tar.gz", "url": "http://just.an.example/django-exceptions-0.4.tar.gz", "requires_python": null, "packagetype": "sdist", "upload_time": "2003-04-14 16:35:12", "digests": {"md5": "29ea3a170a887f88479e0410538ed4fa"}}]}, "urls": [{"filename": "django-exceptions-0.4.tar.gz", "url": "http://just.an.example/django-exceptions-0.4.tar.gz", "requires_python": null, "packagetype": "sdist", "upload_time": "2003-04-14 16:35:12", "digests": {"md5": "29ea3a170a887f88479e0410538ed4fa"}}]}