{"info": {"name": "python-dns-failover", "version": "0.1.0", "requires_dist": ["PySocks (!=1.5.7,>=1.5.6) ; extra == 'socks'", "win-inet-pton ; (sys_platform == \"win32\" and python_version == \"2.7\") and extra == 'socks'"], "requires_python": null, "platform": "UNKNOWN", "summary": null}, "releases": {"0.1.0": [{"filename": "python-dns-failover-0.1.0.tar.gz", "url": "http://just.an.example/python-dns-failover-0.1.0.tar.gz", "requires_python": null, "packagetype": "sdist", "upload_time": "2014-04-01 03:10:52", "digests": {"md5": "8ef8910d09635c21ed5d033723ae671e"}}]}, "urls": [{"filename": "python-dns-failover-0.1.0.tar.gz", "url": "http://just.an.example/python-dns-failover-0.1.0.tar.gz", "requires_python": null, "packagetype": "sdist", "upload_time": "2014-04-01 03:10:52", "digests": {"md5": "8ef8910d09635c21ed5d033723ae671e"}}]}